spring.application.name=backend

#localhost port
server.port=8000

#local sql database url
spring.datasource.url=jdbc:mysql://localhost:3306/yatrago
#local sql username 
spring.datasource.username=root
spring.datasource.password=x
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initializations=true
spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql